version: "3"

services:
  mongodb:
    image: "mongo"
    ports:
    - "27017:27017"

  app:
    depends_on:
      - "mongodb"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/desafio-ror-inovamind
      - gems:/gems

volumes:
  mongodb:
  gems: