development:
  clients:
    default:
      database: desafio_ror_inovamind_development
      hosts:
        - localhost:27017
      options:
test:
  clients:
    default:
      database: desafio_ror_inovamind_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
